
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPER_ART_DIV = 22;
  public static final int PUNTOYCOMA = 37;
  public static final int IMPRIMIR = 7;
  public static final int OPER_ART_SUMA = 19;
  public static final int CONDICION_SINO = 16;
  public static final int OPER_ART_MUL = 21;
  public static final int CICLO_REPETIR = 8;
  public static final int INICIO_CICLO = 12;
  public static final int REPETIR_FIN = 10;
  public static final int OPER_AGRUP_PI = 25;
  public static final int OPER_ASIG_InDe = 24;
  public static final int OPER_AGRUP_PF = 26;
  public static final int NOMBRE_VAR = 36;
  public static final int PAL_FIN_PROG = 3;
  public static final int OPER_AGRUP_LLI = 27;
  public static final int EOF = 0;
  public static final int PAL_VARIABLE = 4;
  public static final int VALOR_FLO = 33;
  public static final int OPER_AGRUP_LLF = 28;
  public static final int error = 1;
  public static final int CICLO_MIENTRAS = 11;
  public static final int FIN_MIENTRAS = 13;
  public static final int ERROR = 38;
  public static final int OPER_AGRUP_CI = 29;
  public static final int VALOR_STRING = 34;
  public static final int OPER_AGRUP_CF = 30;
  public static final int OPER_REL = 18;
  public static final int OPER_ASIG_IGUAL = 23;
  public static final int LEER = 6;
  public static final int PAL_GRUPO = 5;
  public static final int CONDICION_SI = 14;
  public static final int CONDICION_INICIO = 15;
  public static final int VALOR_LOG = 35;
  public static final int OPER_AGRUP_COMA = 31;
  public static final int VALOR_ENT = 32;
  public static final int CONDICION_FIN = 17;
  public static final int REPETIR_HASTA = 9;
  public static final int OPER_ART_RESTA = 20;
  public static final int PAL_INICIO_PROG = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAL_INICIO_PROG",
  "PAL_FIN_PROG",
  "PAL_VARIABLE",
  "PAL_GRUPO",
  "LEER",
  "IMPRIMIR",
  "CICLO_REPETIR",
  "REPETIR_HASTA",
  "REPETIR_FIN",
  "CICLO_MIENTRAS",
  "INICIO_CICLO",
  "FIN_MIENTRAS",
  "CONDICION_SI",
  "CONDICION_INICIO",
  "CONDICION_SINO",
  "CONDICION_FIN",
  "OPER_REL",
  "OPER_ART_SUMA",
  "OPER_ART_RESTA",
  "OPER_ART_MUL",
  "OPER_ART_DIV",
  "OPER_ASIG_IGUAL",
  "OPER_ASIG_InDe",
  "OPER_AGRUP_PI",
  "OPER_AGRUP_PF",
  "OPER_AGRUP_LLI",
  "OPER_AGRUP_LLF",
  "OPER_AGRUP_CI",
  "OPER_AGRUP_CF",
  "OPER_AGRUP_COMA",
  "VALOR_ENT",
  "VALOR_FLO",
  "VALOR_STRING",
  "VALOR_LOG",
  "NOMBRE_VAR",
  "PUNTOYCOMA",
  "ERROR"
  };
}

