/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Generador;

/**
 *
 * @author Jose
 */
public class vizCodigo extends javax.swing.JFrame {

    /**
     * Creates new form vizCodigo
     */
    public vizCodigo(String codigo) {
        initComponents();
        this.txtCodigo.setText(codigo);
        this.setLocationRelativeTo(null);
        this.setSize(300, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vizualizador de código intermedio");
        setType(java.awt.Window.Type.POPUP);

        txtCodigo.setEditable(false);
        txtCodigo.setColumns(20);
        txtCodigo.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtCodigo.setRows(5);
        jScrollPane1.setViewportView(txtCodigo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtCodigo;
    // End of variables declaration//GEN-END:variables
}
